### ISSUE TITLE
onChangeText={(value) => setNicknameInput(value)}

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Maxnarelf/Profile#4]
Можешь делать проще. В таком пример 
```
onChangeText={(value) => setNicknameInput(value)}
```
ты создаешь новую функцию, из-за чего после каждого рендера, у тебя будет создаваться новая функция
А если записать так
```
onChangeText={setNicknameInput}
```
то такого происходить не будет

**Comment by Maxnarelf** [comment]
исправил
