### ISSUE TITLE
Регистрозависимость

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Maxnarelf/Profile#5]
При импорте файла обрати внимание на его название. Если файл называется `bottomNavigation` его нужно импортировать как `./bottomNavigation` а не `./BottomNavigation`. Связано это с тем что системы вроде Linux и MacOS регистрозависивы, а значит файл `BottomNavigation.js` и `bottomNavigation.js` это разные файлы. И только Windows без разницы как он называется

**Comment by Maxnarelf** [comment]
Все исправил, проблема возникла из-за того что переиминовал файл с большой буквы а на гит оно его не подтягивало и отображало с маленькой.
